trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: ubuntu-latest
#     macos:
#       operatingSystem: macos-latest
 

pool:
  vmImage: $(operatingSystem)

stages:
 - stage: Build
   jobs:
   - job : BuildJob
     steps:
      - bash : echo "Hello me"

 - stage: Dev
   jobs:
   - deployment: DevJob
     environment: Dev
     strategy:
      runOnce:
        deploy:
          steps:
            - script: echo hello its dev job deployment 

 - stage: QA
   jobs:
   - deployment: DevJob
     environment: Dev
     strategy:
      runOnce:
        deploy:
          steps:
            - script: echo hello its QA job deployment 