
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo HELLO K8S
  displayName: 'Run a one-line script'
  

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'stroageaccsasio'
    backendAzureRmContainerName: 'conatainerstoragesasio'
    backendAzureRmKey: 'K8S-DEV'
    allowTelemetryCollection: true

