
pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Hello, Build! $(variable-new)
    - bash: echo $(Agent.OS)
    - bash: echo $(Agent.OSArchitecture)
    - bash: echo $(Build.BuildNumber	)
    - bash: echo $(Build.BinariesDirectory	)
    - bash: echo ls -R $(Build.ArtifactStagingDirectory	)

- stage: DevDeploy
  dependsOn: 
  - Build
  - QADeploy
  jobs:
  - job: SecondJob
    steps:
    - bash: echo Hello, DevDeploy! $(variable-new) 

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: ThirdJob
    steps:
    - bash: echo Hello, QADeploy!

- stage: ProdDeploy
  jobs:
  - job: FourthJob
    steps:
    - bash: echo Hello, ProdDeploy!

    
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'System.DefaultWorkingDirectory'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: 'Build.ArtifactStagingDirectory'
