trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Hello, Build! (variable-new)

- stage: DevDeploy
  dependsOn: 
  - Build
  - QADeploy
  jobs:
  - job: SecondJob
    steps:
    - bash: echo Hello, DevDeploy! $(variable-new) 

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: ThirdJob
    steps:
    - bash: echo Hello, QADeploy!

- stage: ProdDeploy
  jobs:
  - job: FourthJob
    steps:
    - bash: echo Hello, ProdDeploy!
